name: Build & Upload iOS App

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.0'
          channel: 'stable'

      - name: Install CocoaPods
        run: sudo gem install cocoapods

      - name: Install dependencies
        run: flutter pub get

      - name: Build iOS (no signing)
        run: flutter build ipa --release --no-codesign

      - name: Install Fastlane
        run: brew install fastlane

      - name: Upload to App Store Connect
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
          APP_BUNDLE_ID: ${{ secrets.APP_BUNDLE_ID }}
          APP_STORE_CONNECT_APP_ID: ${{ secrets.APP_STORE_CONNECT_APP_ID }}
          TEAM_ID: ${{ secrets.TEAM_ID }}
        run: |
          cd ios
          fastlane deliver \
            --username "$APPLE_ID" \
            --app_identifier "$APP_BUNDLE_ID" \
            --ipa "../build/ios/ipa/Runner.ipa" \
            --skip_screenshots \
            --skip_metadata \
            --force \
            --submit_for_review false


