name: Build & Upload iOS App

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show macOS/Xcode
        run: |
          sw_vers
          xcodebuild -version

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.0'
          channel: 'stable'

      - name: Flutter doctor
        run: flutter doctor -v

      - name: Pub get
        run: flutter pub get

      - name: Prepare CocoaPods
        run: |
          sudo gem install cocoapods --no-document
          cd ios
          pod repo update
          pod install

      - name: Build iOS (no signing, verbose)
        run: flutter build ipa --release --no-codesign -v

      - name: Install Fastlane
        run: sudo gem install fastlane -NV

      - name: Upload to App Store Connect
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
          APP_BUNDLE_ID: ${{ secrets.APP_BUNDLE_ID }}
        run: |
          cd ios
          fastlane deliver \
            --username "$APPLE_ID" \
            --app_identifier "$APP_BUNDLE_ID" \
            --ipa "../build/ios/ipa/Runner.ipa" \
            --skip_screenshots \
            --skip_metadata \
            --force \
            --submit_for_review false
